Feature/component-organization
phlask/phlask-map pull request #222
Opened 2021-12-08 03:02 UTC by rh9891

Created new directories for the components based on features (AddTapModal, ClosestTap, Food, FoodFilter, etc.) and reorganized the files. Made additional directories to organize the actions and helper files. Modified how files were being imported. All is working as expected.

2021-12-08 22:53 UTC, tnguyen21 commented
@rh9891 Left a comment with a bug I found. Otherwise, the changes seem to be working as intended. Thanks for the great work!

If you want, we can set up a meeting to talk about PR/code review practices and maybe loop @gcardonag to talk about things we might want to work into the Phlask review workflow.

2021-12-08 22:53 UTC, tnguyen21 requested changes

2021-12-08 22:53 UTC, tnguyen21 commented on src/App.js
> +import Mission from "./components/Pages/Mission";
I'm getting this error when running locally: 
![image](https://user-images.githubusercontent.com/19523341/145303818-8740d46c-4721-4318-9bfc-eb26638a31af.png)

Seems like the directory is named `pages` but the import uses `Pages` -- resulting in this error. Changing it to `pages` resolves the error

2021-12-09 00:15 UTC, gcardonag commented
This MR looks good overall! Thanks for putting in all that time to clean up our file structure. Its already way easier on the eyes locally. 😄 

Regarding the conflicts reported in src/components/Toolbar.js, it seems those are because this branch is still using the older `AddTapModal` component. The following steps will fix your branch locally in case you want to take a jab at solving Git conflicts.
1. Run `git pull`
2. Run `git checkout feature/component-organization`
3. Run `git merge develop`
4. Run `git status` to see the conflict details, there should be 3 files reported.
5. Fix the conflict in `Toolbar.js` by using the version of import that goes `import { AddResourceModal } from "../AddResourceModal";`
6. Run `git add src/components/*` to accept the final version of the conflicted files.
7. Run `git commit` to resolve the conflict and then push up the changes.

If these steps don't work or you have any questions, reach out to me and I can give you a hand or help solve the conflicts on my end once the `Pages` error is resolved.

2021-12-10 00:05 UTC, tnguyen21 commented on src/App.js
> +import Mission from "./components/Pages/Mission";
Fixed in https://github.com/phlask/phlask-map/pull/222/commits/17867d7015463627225ae851af75c5d0e5970dc1

2021-12-10 00:06 UTC, tnguyen21 approved these changes

2021-12-10 00:08 UTC, merged