Tomporvaz/add site button
phlask/phlask-map pull request #331
Opened 2023-07-19 01:15 UTC by tomporvaz

# Pull Request 323

## Change Summary

Changed the Contribute button text to Add Site
Moved textTransform: none up to button sx

## Change Reason

Changed to avoid confusion about contributing information not money.

## Verification [Optional]
![Phlask_2023-07-18 21-10-56](https://github.com/phlask/phlask-map/assets/45155555/094d504a-799a-44ab-9a8c-60d6131c9984)

Related Issue: #323

2023-08-01 23:00 UTC, RNR1 requested changes
Looking great overall, just a few styling changes suggested here

2023-08-01 23:00 UTC, RNR1 commented on src/components/Toolbar/Toolbar.js
> +            <Typography fontSize={'small'}>Resources</Typography>
Curly braces are not necessary for the `fontSize` prop:
```suggestion
            <Typography fontSize="small">Resources</Typography>
```

2023-08-01 23:00 UTC, RNR1 commented on src/components/Toolbar/Toolbar.js
> +            <Typography fontSize={'small'}>Filter</Typography>
Same here:
```suggestion
            <Typography fontSize="small">Filter</Typography>
```

2023-08-01 23:00 UTC, RNR1 commented on src/components/Toolbar/Toolbar.js
> +            <Typography fontSize={'small'}>Search</Typography>
Same here
```suggestion
            <Typography fontSize="small">Search</Typography>
```

2023-08-01 23:00 UTC, RNR1 commented on src/components/Toolbar/Toolbar.js
> +            <Typography noWrap fontSize={'small'}>
Same here:
```suggestion
            <Typography noWrap fontSize="small">
```

2023-08-09 03:10 UTC, tomporvaz commented
@RNR1 I have removed the all of the curly brackets requested, and I also found more in the mobile code.  Searching for curly brackets, I realized that the toolbar is duplicated for mobile, so I updated the contribute button on mobile too.  I think this is complete, but let me know if there is anything else.

2023-08-10 02:14 UTC, RNR1 approved these changes
Thanks! Looking good

2023-08-10 02:15 UTC, merged