Set Phlask DB dynamically
phlask/phlask-map pull request #508
Opened 2024-08-06 22:32 UTC by cjfit

# Pull Request

## Change Summary

- A simple one-liner added to `firebaseConfig.json` that sets the Firebase DB URL based on the presence of an environment variable `REACT_APP_DB_URL`. If `REACT_APP_DB_URL` is not present, it will default to the test database URL.
- The Github action that builds the Docker image was updated to use `REACT_APP_DB_URL`. 
- Unused `utils.js` file removed

## Change Reason

Contributors to the project are typically testing, and any changes made (e.g. adding a resource) will be reflected on the production database. This is not ideal and leads to a lot of data cleanup actions. This change ensures the test database will be used by default unless the developer wants to force use the prod DB.

## Testing
Tested locally the environment variable override works and by resources retrieved/added are done to to the proper DB. 

For the GitHub Action, we'll want to deploy the beta site and then confirm resource changes are made to the production DB.

## Verification [Optional]

Closes #498

2024-08-06 23:40 UTC, vontell requested changes
@gcardonag the current site is only hosted via s3 correct? We were wondering if there is a way to set env vars there.

If the answer is no, @cjfit you can probably use the existing code in utils.js to decide the environment, and then use that inside of the firebaseConfig.js to select the right DB.

2024-08-06 23:45 UTC, cjfit commented
I think env vars may be embedded into the React build - once the action is fixed we could verify this

2024-08-24 12:15 UTC, gcardonag commented
@cjfit is correct, the environment variables will be resolved during the build phase, so the time to set it would be in GitHub actions. The resolved value would be preserved in `bundle.js` during the upload to S3.

Source: https://create-react-app.dev/docs/adding-custom-environment-variables/ 

I tested it locally and got two different lines in `bundle.js` depending on whether the environment variable is set:
- `yarn start` -> `let phlaskDatabaseUrl = ({"NODE_ENV":"development","PUBLIC_URL":"","WDS_SOCKET_HOST":undefined,"WDS_SOCKET_PATH":undefined,"WDS_SOCKET_PORT":undefined,"FAST_REFRESH":true}).REACT_APP_DB_URL || "https://phlask-test.firebaseio.com";`
- `REACT_APP_DB_URL="teststring" yarn start` -> `let phlaskDatabaseUrl = "teststring" || 0;`

2024-08-24 12:16 UTC, gcardonag approved these changes
Approving this and merging as the only test failure is a one-off due to the switch from docker-compose v1 to docker-compose v2 for GitHub Actions runners and is not directly related to this PR.

2024-08-24 12:17 UTC, merged